export const API_ERROR_CODES = {
  UNKNOWN: 'UNKNOWN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  SLUG_TAKEN: 'SLUG_TAKEN',
  PUBLISH_REQUIREMENTS_NOT_MET: 'PUBLISH_REQUIREMENTS_NOT_MET',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  AVATAR_REQUIRED: 'AVATAR_REQUIRED',
  AVATAR_TOO_LARGE: 'AVATAR_TOO_LARGE',
  AVATAR_INVALID_TYPE: 'AVATAR_INVALID_TYPE',
  WORK_FILE_REQUIRED: 'WORK_FILE_REQUIRED',
  WORK_FILE_TOO_LARGE: 'WORK_FILE_TOO_LARGE',
  WORK_INVALID_TYPE: 'WORK_INVALID_TYPE',
  WORK_NOT_FOUND: 'WORK_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export type ApiFieldError = {
  path: string;
  message: string;
};

export type ApiErrorResponse = {
  statusCode: number;
  code: ApiErrorCode;
  message: string;
  errors?: ApiFieldError[];
};
