-- AlterTable
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "medium" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "series" TEXT;
